export const CREATE_TODO_ITEM = 'CREATE_TODO_ITEM';
export const UPDATE_TODO_ITEM = 'UPDATE_TODO_ITEM';
export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM';

export const CLEAR_TODO_LIST = 'CLEAR_TODO_LIST';
export const START_RECORDING_ACTIONS = 'START_RECORDING_ACTIONS';
export const STOP_RECORDING_ACTIONS = 'STOP_RECORDING_ACTIONS';
export const PLAY_RECORDED_ACTIONS = 'PLAY_RECORDED_ACTIONS';
export const CLEAR_RECORDED_ACTIONS = 'CLEAR_RECORDED_ACTIONS';
